# app configuration
app:
  # mode should be one of [debug release test]
  mode: debug
  # app name
  name: dy-back
  # if swagger api doc enable, the apidoc can visit on http://http.address/swagger/index.html
  swagger: true
  ipv4: 111.230.33.57
#  ipv4: 192.168.137.255
  static:
    baseSrc: ./assets/
# mysql configuration
mysql:
#  url: 127.0.0.1:3306
  url: 111.230.33.57:3306
  database: dy
  username: root
  password: root
# redis configuration
redis:
  addr: 111.230.33.57:6379
#  addr: 127.0.0.1:6379
  password:
  DB: 0
  poolSize: 30
  minIdleConn: 30
# log configuration
log:
  # min level should be one of [fatal panic error warn info debug trace]
  level: debug

# auth configuration
auth:
  jwt:
    issuer: Octopus
    expireTime: 24

smtp:
  from: 1687723655@qq.com
  password: kposdhxgsmageabf
  host: smtp.qq.com
  port: 25